config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { 
  	registrations: 'registrations', 
  	confirmations: 'confirmations'
  }
  root 'users#show'
  get 'users/:id' => 'users#show'
  resources :interviews, only: :show
  resources :upcomings, only: [:new,:create]
  delete 'upcomings/:id' => 'upcomings#destroy', as: "upcoming_destroy"

end

app/models/interview.rb
class Interview < ActiveRecord::Base

	has_many :user_interviews
	has_many :users, through: :user_interviews
	validates :date, :question_1, :question_2, presence: true

	# def make_the_interview

	# end

end

app/models/upcoming.rb
class Upcoming < ActiveRecord::Base
	belongs_to :user

	validates :user_id, presence: true
	validates :date, presence: true

	validate :valid_date?

	def valid_date?
		date.tuesday? || date.thursday?
	end

	def next_day(day)
		date  = Date.parse(day)
	  days_between = date > Date.today ? 0 : 7
	  date + days_between
	end

	def following_day(day)
		next_day(day) + 7
	end

	def allowed_to_delete?
		Date.tomorrow != self.next_day('Tuesday') || 2.days.from_now != self.following_day('Tuesday') || Date.tomorrow != self.next_day('Thursday') || 2.days.from_now != self.following_day('Thursday') ? true : false

	end

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # , :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :confirmable
  has_many :user_interviews
  has_many :interviews, through: :user_interviews
  has_many :upcomings

  validates :email, :name, presence: true

end

app/models/user_interview.rb
class UserInterview < ActiveRecord::Base
	belongs_to :user
	belongs_to :interview
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_action :authenticate_user!
	
  def after_sign_out_path_for(resource_or_scope)
    new_user_session_path
  end

end

app/controllers/confirmations_controller.rb
class ConfirmationsController < Devise::ConfirmationsController
	skip_before_action
	def new
		super
	end

end

app/controllers/interviews_controller.rb
class InterviewsController < ApplicationController

	def show
		@interview = Interview.find(params[:id])
		@users = @interview.users
		if @users.length == 3
			@user_questions = {
				@users[0] => @interview.question_1,
				@users[1] => @interview.question_2,
				@users[2] => @interview.question_3
			}
		else
			@user_questions = {
				@users[0] => @interview.question_1,
				@users[1] => @interview.question_2
			}
		end
	end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController


	private

	def sign_up_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end
  
	def after_inactive_sign_up_path_for(resource)
    new_user_confirmation_path
  end

  def account_update_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation, :current_password)
  end
end

app/controllers/upcomings_controller.rb
class UpcomingsController < ApplicationController

	def new
		@upcoming = Upcoming.new
		@next_tuesday = @upcoming.next_day('Tuesday')
		@next_thursday = @upcoming.next_day('Thursday')
		@following_tuesday = @upcoming.following_day('Tuesday')
		@following_thursday = @upcoming.following_day('Thursday')
	end

	def create
		upcoming_params.each do |label,date|
			
				@upcoming = Upcoming.new(date: date, user_id: current_user.id)
				@upcoming.save
		end
		redirect_to action: "show", controller: "users", id: current_user.id
	end

	def destroy
		Upcoming.destroy(params[:id])
		redirect_to root_path
	end


	private

	def upcoming_params
		params[:upcoming].permit('1_tuesday', '1_thursday', '2_tuesday', '2_thursday')
	end	
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	
	def show
		@user = User.includes(:upcomings,:interviews).find(current_user.id)
	end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/interviews/show.html.erb
<h1>Interview Scheduled for <%= @interview.date %></h1>

<p><%= link_to "Home", root_path %></p>

<p>The group for this interview will be: </p>
<ul>
	<% @users.each do |user| %>
		<li><br />
			<%= user.name %>
			<%= user.email %>
		</li>
	<% end %>
</ul>

<p>The question you will be asking is: </p>
<%= @user_questions[current_user] %>


<% if @users.length == 3 %>
	<p>You will ask the person beneath your name this question, if you are the last person on the list, you will ask the first person.</p>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>MockInterviews</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <link href='https://fonts.googleapis.com/css?family=Varela+Round' rel='stylesheet' type='text/css'>
  <script src="https://use.fontawesome.com/923b5ec59b.js"></script>
</head>
<body>
<p class="notice"><%= notice %></p>
<p class="alert"><%= alert %></p>
<%= yield %>

<footer>
	<div class="description">
		<p>App built for Dev Bootcamp Alumni to practice whiteboarding technical interview questions with a partner. Sessions happen twice a week, and those registered for a session are paired and assigned a question to ask their partner two days before the session.</p>
	</div>
	<div class="credit">
		<p>Built By John Maguire: <a href='https://github.com/jm96441n'>Github</a> <a href='https://www.linkedin.com/in/johnmaguire1'>LinkedIn</a> <a href='http://johnmaguiredeveloper.com/'>Website</a></p>
		<p>Designed By Lisa Buch: <a href='https://github.com/LisaBee224'>Github</a> <a href='https://www.linkedin.com/in/lisabuch'>LinkedIn</a> <a href='http://www.LisaBee224.github.io/'>Website</a></p>
	</div>
	<div class="contact">
		<p>Contact Us!</p>
		<a href="mailto:john@johnmaguiredeveloper.com">John</a>
		<a href="mailto:lisakbuch@gmail.com">Lisa</a>
	</div>
	<div>
		<p>Check out the source code <a href="https://github.com/jm96441n/dbc_mock_interviews">HERE</a>!</p>
	</div>
</footer>
</body>
</html>

app/views/upcomings/new.html.erb
<div id="header">
<h1>Register For Upcoming Interview Sessions</h1>
</div>
<div  class="home_link">
	<%= link_to "Home", root_path %>
</div>
<div id="container">
	<div id="schedcontent">
<h3>Every Tuesday and Thursday at 11am</h3>

<form action="/upcomings" method="POST">
	<input type="hidden" name="authenticity_token" value="d+9wv7RwRnMflcGeegV1IkLMxiutFy6twk0ysG6WPq69irNDh47z6DWCP2Q2tXwf1DgYI6frirYwKYFsY91WEQ==">

<div class="dates">
	<% if Date.tomorrow != @next_tuesday && 2.days.from_now.to_date != @next_tuesday %>

		<div>
			<span>Tuesday  <%= @next_tuesday.month %>/<%= @next_tuesday.day %> </span>
			<input type="checkbox" name="upcoming[1_tuesday]" value="<%= @next_tuesday %>" />
		</div>
	<% end %>

	<% if Date.tomorrow != @next_thursday && 2.days.from_now.to_date != @next_thursday %>
		<div>
		<span>Thursday  <%= @next_thursday.month %>/<%= @next_thursday.day %> </span>
		<input type="checkbox" name="upcoming[1_thursday]" value="<%= @next_thursday %>" />
	</div>
	<% end %>

	<div>
		<span>Tuesday  <%= @following_tuesday.month %>/<%= @following_tuesday.day %> </span>
		<input type="checkbox" name="upcoming[2_tuesday]" value="<%= @following_tuesday %>" />
	</div>
	<div>
		<span>Thursday  <%= @following_thursday.month %>/<%= @following_thursday.day %> </span>
		<input type="checkbox" name="upcoming[2_thursday]" value="<%= @following_thursday %>" />
		</div>
	</div>
	<div class="actions">
		<input type="submit" value="Schedule Those Interviews!"/>
	</div>
</form>
</div>
</div>

app/views/users/show.html.erb
<h1> Hello <%= current_user.name %></h1>


<div id="containerinfo">

<p><%= link_to "Sign Out", destroy_user_session_path(current_user.id), method: :delete %></p>


<p>Registered Interview Dates</p>



<p id="userdates">Registered Interview Dates</p>
	<% if @user.upcomings.empty? %>
		<p><i>snap! you have no upcoming interviews</i></p>
	<%else%>
		<% @user.upcomings.each do |upcoming| %>
			<% if upcoming.allowed_to_delete? %>
				<li><%= upcoming.date.strftime("%A")%> <%= upcoming.date.month %>/<%= upcoming.date.day %>  <%= link_to "Delete", upcoming_destroy_path(upcoming.id), method: :delete %></li>
			<% end %>
		<% end %>
	<% end %>

<% @user.interviews.reverse.each do |interview| %>
	<li><%= link_to "#{interview.date}", interview_path(interview.id) %></li>
<% end %>


	<div id="reg">
		<%= link_to 'Register for Upcoming Interview Sessions', new_upcoming_path %>
	</div>
</div>

</div>